openapi: 3.0.2
info:
  title: telegram bot
  version: 0.1.0
paths:
  /ads:
    get:
      summary: Get Ads
      operationId: get_ads_ads_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}

