openapi: 3.0.2
info:
  title: 5DollarJobs Plugin
  version: 0.1.0
paths:
  /ads:
    get:
      summary: Get Ads
      operationId: get_ads_ads_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /create/job:
    get:
      summary: Create Job
      operationId: create_job_create_job_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  create_job_link: 
                    type: string
              

